### ISSUE TITLE
sam build fails with `Error: JavaMavenWorkflow:CopySource - [Errno 20] Not a directory`

### ISSUE THREAD

**Issue by lestephane** [awslabs/aws-lambda-builders#113]
Getting an error when running `sam build` in an existing project of mine,
where the sam template has a CodeUri that points to a JAR file in a reactor build submodule.

**Steps to reproduce the issue:**

1. existing java maven project using reactor builds with
  1.1 a shaded jar generated in a maven submodule's target directory
      (`<project-top-level>/lambdas/mainlambda/target/lambda.jar` in my case)
  1.2 a template.yaml in the `<project-top-level>` directory using
     `CodeUri: lambdas/mainlambda/target/lambda.jar`
2. cd `<project-top-level>`
3. `sam build --debug`

**Observed result:**
```text
2019-04-28 19:31:55 Collected default values for parameters: {}
2019-04-28 19:31:55 12 resources found in the template
2019-04-28 19:31:55 Found Serverless function with name='LatestFunction' and CodeUri='lambdas/mainlambda/target/lambda.jar'
2019-04-28 19:31:55 Found Serverless function with name='LiveFunction' and CodeUri='lambdas/mainlambda/target/lambda.jar'
2019-04-28 19:31:55 Found Serverless function with name='TestRunnerFunction' and CodeUri='lambdas/testlambda/target/lambda.jar'
2019-04-28 19:31:55 Building resource 'LatestFunction'
2019-04-28 19:31:55 Looking for a supported build workflow in following directories: ['<scrubbed>/GitRepos/someproject/lambdas/mainlambda/target/lambda.jar', '<scrubbed>/GitRepos/someproject']
2019-04-28 19:31:55 Loading workflow module 'aws_lambda_builders.workflows'
2019-04-28 19:31:55 Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2019-04-28 19:31:55 Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
2019-04-28 19:31:55 Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
2019-04-28 19:31:55 Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
2019-04-28 19:31:55 Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
2019-04-28 19:31:55 Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
2019-04-28 19:31:55 Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
2019-04-28 19:31:55 Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
2019-04-28 19:31:55 Found workflow 'JavaMavenWorkflow' to support capabilities 'Capability(language='java', dependency_manager='maven', application_framework=None)'
2019-04-28 19:31:55 Running workflow 'JavaMavenWorkflow'
2019-04-28 19:31:55 Running JavaMavenWorkflow:CopySource
2019-04-28 19:31:55 JavaMavenWorkflow:CopySource raised unhandled exception
Traceback (most recent call last):
  File "<scrubbed>/.virtualenvs/aws/lib/python3.6/site-packages/aws_lambda_builders/workflow.py", line 248, in run
    action.execute()
  File "<scrubbed>/.virtualenvs/aws/lib/python3.6/site-packages/aws_lambda_builders/actions.py", line 101, in execute
    copytree(self.source_dir, self.dest_dir, ignore=shutil.ignore_patterns(*self.excludes))
  File "<scrubbed>/.virtualenvs/aws/lib/python3.6/site-packages/aws_lambda_builders/utils.py", line 43, in copytree
    names = os.listdir(source)
NotADirectoryError: [Errno 20] Not a directory: '<scrubbed>/GitRepos/someproject/lambdas/mainlambda/target/lambda.jar'
```

**Expected result:**

I would expect it to run the equivalent of 

```bash
(in <project-top-level> folder)
mvn package -pl lambdas/mainlambda -am 
```
Which is what i run when I want to just build lambda.jar

- `-pl lambdas/mainlambda` because that is the module folder of the `target` folder where `lambda.jar` is located. 
- `-am` because otherwise reactor builds will fail
- `-Dmaven.test.skip=true` because when run from the aws-toolkit, you don't want to rerun the whole test suite (?)

This `sam build` failure is preventing me from creating launch configurations using aws-toolkit for Intellij.

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

I don't believe my environment makes any difference in this issue, but I'll answer any request for more information if that is deemed necessary

**Comment by Ghilteras** [comment]
same issue here, the only way I made it work is to have my handler implement `RequestHandler`

**Comment by markusgulden** [comment]
You need to point the CodeUri attribute in your template.yaml to your pom.xml, not to */target/lambda.jar.
That solved the issue for me, at least.

**Comment by Ghilteras** [comment]
`sam local` does not work if you point the template `CodeUri` the `pom.xml`

It seems only AWS Toolkit would work like this, which is confusing because then you have to change your template based on whether you invoke Sam from your IDE or from the cli (or have 2 different templates).

**Comment by zeelmavani** [comment]
Facing the same issue, 
if I give a path to pom.xml then Sam local does not work,
and if I give the path to jar then sam build does not work. Any good way to do this?

**Comment by jaapspiering** [comment]
> Facing the same issue,
> if I give a path to pom.xml then Sam local does not work,
> and if I give the path to jar then sam build does not work. Any good way to do this?

You can use a Parameter in the template.yml file and specify the correct value for a ``sam build``  using ``--parameter-overrides``. See the docs for this: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html

**Comment by jaxley** [comment]
Figured an explicit workaround example would be useful.

> > Facing the same issue,
> > if I give a path to pom.xml then Sam local does not work,
> > and if I give the path to jar then sam build does not work. Any good way to do this?
> 
> You can use a Parameter in the template.yml file and specify the correct value for a `sam build` using `--parameter-overrides`. See the docs for this: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
Snippet from template.yaml:

```
Parameters:
  CodeUri:
    Description: CodeUri - change this to pom.xml directory for AWS Toolkit IDE plugin with --parameter-overrides "CodeUri"
    Type: String
    Default: lambda/target/foo.jar
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: !Sub ${CodeUri}
....
```

Invoking with sam (from project directory containing pom.xml; otherwise, choose a different directory *relative to the template.yaml file location*):

`sam build --debug --parameter-overrides "ParameterKey=CodeUri,ParameterValue=."`

**Comment by harry-wright** [comment]
I too am having this issue. Will attempt the fix mentioned. Java8 + IntelliJ + AWS Toolkit Plugin, trying to test Lambda's locally using docker containers.

**Comment by harry-wright** [comment]
Okay so the @jaxley fix worked. Although using the base as the override in the test, (as opposed to using the target executable as the override in the maven build), is then causing the 'Deploy serverless application' feature (when right clicking template.yml) to fail.

So to clear things up, the default CodeUri needs to be the source root with the pom, then this needs to be overriden for a deployment. This is assumed. I have still not got round to fixing this but will follow up.
