### ISSUE TITLE
maven_resolver.py raises "No Maven executable found!", but Maven is already install

### ISSUE THREAD

**Issue by peniakoff** [awslabs/aws-lambda-builders#156]
**Description:**
I can not build Lambda via AWS toolkit (SAM) in the InteliJ. Build fails with an error `ValueError: No Maven executable found!`, but Maven is already install and the terminal for `which mvn` returns correct path `.../.sdkman/candidates/maven/current/bin/mvn`. I'm not a Python developer, so I really don't know, how can I fix this bug. Below attached the log after run the lambda.

**Steps to reproduce the issue:**
1. Choose YAML template for lambda.
2. Run the Lambda from InteliJ.
3. See result in the "Build Output".

**Observed result:**
`Traceback (most recent call last):`
`File "/home/linuxbrew/.linuxbrew/bin/sam", line 11, in <module> load_entry_point('aws-sam-cli==0.40.0', 'console_scripts', 'sam')()`
`File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/click/core.py", line 764, in __call__ return self.main(*args, **kwargs)`
`File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/click/core.py", line 717, in main rv = self.invoke(ctx)`
`File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/click/core.py", line 1137, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx))`
`File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/click/core.py", line 956, in invoke return ctx.invoke(self.callback, **ctx.params)`
`File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/click/core.py", line 555, in invoke return callback(*args, **kwargs)`
`File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func return ctx.invoke(f, obj, *args, **kwargs)`
`File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/click/core.py", line 555, in invoke return callback(*args, **kwargs)`
`File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 96, in wrapped raise exception  # pylint: disable=raising-bad-type`
`File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 62, in wrapped return_value = func(*args, **kwargs)`
`File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/samcli/commands/build/command.py", line 127, in cli mode,`
`File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/samcli/commands/build/command.py", line 192, in do_cli artifacts = builder.build()`
`File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/samcli/lib/build/app_builder.py", line 104, in build lambda_function.runtime)`
`File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/samcli/lib/build/app_builder.py", line 195, in _build_function runtime)`
`File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/samcli/lib/build/app_builder.py", line 216, in _build_function_in_process     mode=self._mode)`
`File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/builder.py", line 115, in build return workflow.run()`
`File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 48, in wrapper exec_paths = binary_path.resolver.exec_paths if not binary_path.path_provided else binary_path.binary_path`
`File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/workflows/java_maven/maven_resolver.py", line 21, in exec_paths raise ValueError("No Maven executable found!")`
`ValueError: No Maven executable found!`

**Expected result:**
Lambda runs.

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
Linux 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by peniakoff** [comment]
Reason for that is AWS Toolkit takes path from the sh, not profile's bash. When we are using tool like SDKMAN!, path to the Maven is set when profile is loading, not with the system root. For solution I have created link to the executable mvn in the `/usr/bin`, which is loaded by default with the system. Now it works, but generally maybe good solution will be implement searching for all available PATHs?
