### ISSUE TITLE
Unable to find distutils.util after upgrading from Python 3.7 to 3.8

### ISSUE THREAD

**Issue by jingxue** [awslabs/aws-lambda-builders#173]
After upgrading to Pop OS(Ubuntu) 20.04, Python was upgraded to 3.8. Running `sam build` produces the following error:
```
Running PythonPipBuilder:ResolveDependencies

Build Failed
Error: PythonPipBuilder:ResolveDependencies - Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pip/_internal/main.py", line 14, in main
    from pip._internal.utils.entrypoints import _wrapper
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/entrypoints.py", line 3, in <module>
    from pip._internal.cli.main import main
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 19, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils.util'
```

I do have `distutils` installed under `/usr/lib/python3.8`.  I noticed that the traceback above was produced by pip from `python3/dist-packages`, however I do have a later version of pip installed under my `.local/lib/python3.8/site-packages`.  The two symptoms together make me think that when the builder runs pip as a subprocess, it's not picking up any 3.8 packages.

I have tried the sample project in a clean install 20.04 environment, and SAM builds fine there. So this is not necessarily a SAM issue, and must be something broken during the upgrade. I'm just hoping you can point me to how python/pip is executed by the builder.

**Comment by jingxue** [comment]
Duh... I forgot to update the 'python 3.7' references in my template.yml.  I wish there could have been some more obvious message though.
